server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    #实列名字
    instance-id: OrederMain80
spring:
  application:
    name: OrederMain80