server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    #实列名字
    instance-id: PaymentMain8002
spring:
  application:
    name: PaymentMain